### ISSUE TITLE
Cant change thumbnails

### ISSUE THREAD

**Issue by nebulous42069** [jmooremcc/plugin.program.super.favourites#11]
After updating to 2.3.3, I am not able to set thumbnails for SF's. I get the following error when using Edit Superfavorite/ Choose thumbnail/ and browse to the path I store my thumbnails. After selecting the thumbnail, it throws this error.
`2023-08-25 16:16:01.454 T:12904   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<-- - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS! Error Type: <class 'OSError'> Error Contents: [Errno 22] Invalid argument: 'special://home/addons/resource.images.skinicons.wide/resources/APPTV/ustvgo/sec.jpg' Traceback (most recent call last): File "C:\Users\xxx\AppData\Roaming\Kodi\addons\plugin.program.super.favourites\default.py", line 3115, in <module> doRefresh = editFave(file, cmd, name, thumb) File "C:\Users\xxx\AppData\Roaming\Kodi\addons\plugin.program.super.favourites\default.py", line 1560, in editFave return thumbFave(file, cmd) File "C:\Users\xxx\AppData\Roaming\Kodi\addons\plugin.program.super.favourites\default.py", line 1063, in thumbFave image = getImage() File "C:\Users\xxx\AppData\Roaming\Kodi\addons\plugin.program.super.favourites\default.py", line 946, in getImage return cacheImage(image) File "C:\Users\xxx\AppData\Roaming\Kodi\addons\plugin.program.super.favourites\imagecache.py", line 80, in cacheImage copyfile(path, newfname) File "C:\Program Files\Kodi\system\python\Lib\shutil.py", line 264, in copyfile with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst: OSError: [Errno 22] Invalid argument: 'special://home/addons/resource.images.skinicons.wide/resources/APPTV/ustvgo/sec.jpg' -->End of Python script error report<--`

**Comment by jmooremcc** [comment]
> After updating to 2.3.3, I am not able to set thumbnails for SF's. I get the following error when using Edit Superfavorite/ Choose thumbnail/ and browse to the path I store my thumbnails. After selecting the thumbnail, it throws this error. `2023-08-25 16:16:01.454 T:12904 error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<-- - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS! Error Type: <class 'OSError'> Error Contents: [Errno 22] Invalid argument: 'special://home/addons/resource.images.skinicons.wide/resources/APPTV/ustvgo/sec.jpg' Traceback (most recent call last): File "C:\Users\xxx\AppData\Roaming\Kodi\addons\plugin.program.super.favourites\default.py", line 3115, in <module> doRefresh = editFave(file, cmd, name, thumb) File "C:\Users\xxx\AppData\Roaming\Kodi\addons\plugin.program.super.favourites\default.py", line 1560, in editFave return thumbFave(file, cmd) File "C:\Users\xxx\AppData\Roaming\Kodi\addons\plugin.program.super.favourites\default.py", line 1063, in thumbFave image = getImage() File "C:\Users\xxx\AppData\Roaming\Kodi\addons\plugin.program.super.favourites\default.py", line 946, in getImage return cacheImage(image) File "C:\Users\xxx\AppData\Roaming\Kodi\addons\plugin.program.super.favourites\imagecache.py", line 80, in cacheImage copyfile(path, newfname) File "C:\Program Files\Kodi\system\python\Lib\shutil.py", line 264, in copyfile with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst: OSError: [Errno 22] Invalid argument: 'special://home/addons/resource.images.skinicons.wide/resources/APPTV/ustvgo/sec.jpg' -->End of Python script error report<--`

I've tried replicating the issue on my Windows 11 system and on my Raspberry Pi system, and had no problem setting a thumbnail. I'd appreciate it if you would give me a link to your entire log so that I can see what's going on.

**Comment by nebulous42069** [comment]
Sure. So heres a log. So just to explain.. I fresh installed Kodi, added the SF repo. Added special://home as a source in file manager. Installed resource.images.skinicons.wide. (This is where I store my icons). Same issue when I go to change a thumbnail. Here is the full log zipped: 
[kodi.zip](https://github.com/jmooremcc/plugin.program.super.favourites/files/12479586/kodi.zip)

**Comment by nebulous42069** [comment]
Heres the log in Pastebin: https://pastebin.com/jYyHnnpA

**Comment by nebulous42069** [comment]
I always add special://home to file manager so I can navigate to the thumbnail easily when editing Superfavorites, also so the path is never device dependent. It has always worked fine in the past.

**Comment by nebulous42069** [comment]
I also tried putting the icons in the special://home/Media folder and throws the same error.

**Comment by jmooremcc** [comment]
Why are you using this method to specify a path instead of a normal path specification?
`special://home/addons/resource.images.skinicons.wide/resources/icons/3now.png`

Were you able to use this method in previous versions?

**Comment by jmooremcc** [comment]
I've added an image cache system that facilitates the backup and restore of icons and this system expects a normal directory path. With the new caching system, portability of icons and fanart is pretty much guarantied.

 I'd like to know, however, how you were able to specify the special path while selecting the image from within the browser.

**Comment by nebulous42069** [comment]
> Why are you using this method to specify a path instead of a normal path specification? `special://home/addons/resource.images.skinicons.wide/resources/icons/3now.png`
> 
> Were you able to use this method in previous versions?

Yes, ive always used this way. How else could you navigate to a special path to set a thumbnail if a special path isnt added to File manager first?? I cannot navigate to a special path normally through SF's unless I do, unless you know of a way?

**Comment by nebulous42069** [comment]
Without special://home in file manager you are not able to navigate to the special path. When you choose edit thumbnail it opens the C: drive on Windows and you would need to navigate all the way through Appdata/Roaming/Kodi/ to get there, then the path is not special.

**Comment by nebulous42069** [comment]
Unless you could make it open special path by default when you go to choose a thumbnail, but im guessing the same problem would remain. This has always worked in previous versions.

**Comment by nebulous42069** [comment]
Here is a video on the current version of SF and how to navigate to special://home. (You just go back one directory to get to special): https://video.hardlimit.com/w/rtbPaLeS5CsirkQXU8cEeo

**Comment by nebulous42069** [comment]
Here is a video of the same thing, but with SF version 2.26. This shows how it always worked before the latest update... https://video.hardlimit.com/w/wXg3UJNrXswS3nDrV9zwb3

**Comment by nebulous42069** [comment]
> Why are you using this method to specify a path instead of a normal path specification? `special://home/addons/resource.images.skinicons.wide/resources/icons/3now.png`




> Why are you using this method to specify a path instead of a normal path specification? `special://home/addons/resource.images.skinicons.wide/resources/icons/3now.png`
> 
Because if I dont specify the special path, then it would only work on my device. When I copy my setup to my other devices or friends devices, the paths would be invalid. Thats usually what special paths are used for.

**Comment by jmooremcc** [comment]
> 

That's what the new image cache system was designed to solve. It allows you to export your settings to a file and then import the file on a different system without losing your fanart and icons. Give it a try.

**Comment by nebulous42069** [comment]
I guess the thing is, to choose an icon and being forced to navigate though the whole file system to choose an icon is a much more tedious process than if I was to create a special path. and navigate to the folder with a couple clicks. I already have hundreds of SF shortcuts with chosen icons. But I see what your saying. I guess I can move all my icons over to the ImageCache folder, and then use Notepad++ to search and replace special://home/addons/resource.images.wide/icons (where they are currently kept, to special://home/userdata/addon_data/plugin.program.super.favourites/ImageCache/icons instead.  Since I wouldnt want two folders of the same icons anyway. But not sure how that works for the ImageCach folder. I have all my icons organized in folders and subfolders, and SF is probably going to just create another copy of the image and put it in the root of ImageCache. I guess I prefered handling my icon directory myself as I keep it organized and easily accessible using special paths. 
<img width="295" alt="Screenshot_1" src="https://github.com/jmooremcc/plugin.program.super.favourites/assets/125807561/7302ab31-9329-4aea-8aaf-93be37c9ba40">

**Comment by nebulous42069** [comment]
I guess my preference would be to still be able to use my special paths and have the ability to disable the ImageCaching feature in SF, so I can manage them myself.

**Comment by nebulous42069** [comment]
As you can see here in my sources.xml, I have multiple shortcuts of special paths for easy access to all my icons with one click... And my icons are all organized in these folders
<img width="524" alt="Screenshot_2" src="https://github.com/jmooremcc/plugin.program.super.favourites/assets/125807561/c7707ddc-cff3-46f3-90ce-247d939e53b8">

**Comment by jmooremcc** [comment]
> Unless you could make it open special path by default when you go to choose a thumbnail, but im guessing the same problem would remain. This has always worked in previous versions.

The image cache system came about from a user request to be able to export/import icons & fanart.

However, I've got an idea I'd like to try to resolve the issue you are experiencing.
In order to replicate your environment, can you send me an xml file that references 4 images along with instructions on how you set it up. If you could zip it altogether that would be appreciated. Once I can recreate the error you are experiencing, I'll be able to test my solution.

**Comment by nebulous42069** [comment]
> > Unless you could make it open special path by default when you go to choose a thumbnail, but im guessing the same problem would remain. This has always worked in previous versions.
> 
> The image cache system came about from a user request to be able to export/import icons & fanart.
> 
> However, I've got an idea I'd like to try to resolve the issue you are experiencing. In order to replicate your environment, can you send me an xml file that references 4 images along with instructions on how you set it up. If you could zip it altogether that would be appreciated. Once I can recreate the error you are experiencing, I'll be able to test my solution.

**Comment by nebulous42069** [comment]
You will see how much i depend on SF in my setup..

**Comment by nebulous42069** [comment]
Its made on Kodi 20. Not sure what you mean by an xml referencing 4 images.

**Comment by nebulous42069** [comment]
So if you try this setup, this is what youll see. Open Superfavorites, then try to change a thumb like this..

**Comment by nebulous42069** [comment]
Hers my SF addon_data if thats what you meant?

**Comment by nebulous42069** [comment]
If you need anything else let me know, thanks!

**Comment by jmooremcc** [comment]
As I mentioned previously, I'd like to replicate your environment so that I can duplicate the issue you are experiencing. When I watched your video where you were selecting an icon, you went to special://home. 

According to your log, you're running Kodi on a Windows system. I'm running Kodi on Windows 11 and have never seen anything other than normal directory paths. How did you set up your system to do this?

**Comment by nebulous42069** [comment]
> As I mentioned previously, I'd like to replicate your environment so that I can duplicate the issue you are experiencing. When I watched your video where you were selecting an icon, you went to special://home.
> 
> According to your log, you're running Kodi on a Windows system. I'm running Kodi on Windows 11 and have never seen anything other than normal directory paths. How did you set up your system to do this?

Ok, so to use special paths, you simply add special://home to Kodi file manager. After you do this you can navigate directly to the Kodi folder when choosing icons or installing zips or anything else you have directly in the Kodi folder. Watch this video. I started from a fresh install of Kodi, added special path to file manager and used this special path to install your repo and choose thumbs in SF... https://video.hardlimit.com/w/tuBVBzT6eAE1vERkrz8mZd

**Comment by jmooremcc** [comment]
Thank you for the information. I was able to replicate the problem and have developed a solution. The solution I've developed converts the special path to an absolute path and stores the image in the image cache. Remember, the purpose of the image cache system is to facilitate importing/exporting SF folders. Not only are images copied to the image cache, but the folder.cfg file in each folder now references the image cache for local icons.

However, something you said earlier about making the new caching system optional has me thinking about it. I've not heard of anyone doing what you are doing, using special paths as an end user. I am familiar with special paths because of programming addons, but it never crossed my mind that it could be used by end users in SF. 

If I add the ability to enable/disable image caching in the settings, how would you expect that setting to work? Would it's default value be On or Off?
One thing I'm certain of is that turning it On would require a restart of the SF addon and turning it Off would remove the image cache folder and any references to it in the folder.cfg files.
What are your thoughts on this?

**Comment by nebulous42069** [comment]
Awesome!! Im glad you were able to replicate. Im surprised more people dont use special paths. Makes it much easier to navigate to the Kodi folder for doing various things. Plus anything you use special paths for works universally across different operating systems. As for the ON/OFF caching option, I would prefer it off by default, but thats just me. Either way, if I can turn it off and continue using my own folder for icons I will be happy. I use my icon folder for many various things, not just Super Favourites, so having duplicates in the SF cache folder doesnt appeal to me. Appreciate your help on this!!

**Comment by nebulous42069** [comment]
While your on the subject, another big flaw introduced with this new update. Every skin shortcut path or widget now uses the full OS file path. I was wondering why all my widgets and shortcuts that point to SF shortcuts no longer work on other devices. I create my setup on Windows 11 and then transfer the setup to other devices, and now none of those shortcuts will work because of this. Now when I create a shortcut to a SF folder using skin settings it writes the whole path rather than special paths like all previous versions of SF used to do correctly. Now this is what the path writes for example:
`     "mainmenu",
        "24-7",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.program.super.favourites/?label=24-7&mode=400&path=C%3A%5CUsers%5Cxxx%5CAppData%5CRoaming%5CKodi%5Cuserdata%5Caddon_data%5Cplugin.program.super.favourites%5CSuper+Favourites%5C24-7&image=special%3A%2F%2Fhome%2Faddons%2Fresource.images.skinicons.wide%2Fresources%2Ficons%2F247.png&fanart=special%3A%2F%2Fhome%2Faddons%5Cplugin.video.fidoK19%5Cfanart.jpg&content_type=\",return)"`

**Comment by jmooremcc** [comment]
> While your on the subject, another big flaw introduced with this new update. Every skin shortcut path or widget now uses the full OS file path. I was wondering why all my widgets and shortcuts that point to SF shortcuts no longer work on other devices. I create my setup on Windows 11 and then transfer the setup to other devices, and now none of those shortcuts will work because of this. Now when I create a shortcut to a SF folder using skin settings it writes the whole path rather than special paths like all previous versions of SF used to do correctly. Now this is what the path writes for example: ` "mainmenu", "24-7", "translatedPath", "ActivateWindow(Videos,\"plugin://plugin.program.super.favourites/?label=24-7&mode=400&path=C%3A%5CUsers%5Cxxx%5CAppData%5CRoaming%5CKodi%5Cuserdata%5Caddon_data%5Cplugin.program.super.favourites%5CSuper+Favourites%5C24-7&image=special%3A%2F%2Fhome%2Faddons%2Fresource.images.skinicons.wide%2Fresources%2Ficons%2F247.png&fanart=special%3A%2F%2Fhome%2Faddons%5Cplugin.video.fidoK19%5Cfanart.jpg&content_type=\",return)"`

I suspected that would be the case. My plan is to make the cache system ignore special paths which should resolve the issue you are reporting.

**Comment by nebulous42069** [comment]
> > While your on the subject, another big flaw introduced with this new update. Every skin shortcut path or widget now uses the full OS file path. I was wondering why all my widgets and shortcuts that point to SF shortcuts no longer work on other devices. I create my setup on Windows 11 and then transfer the setup to other devices, and now none of those shortcuts will work because of this. Now when I create a shortcut to a SF folder using skin settings it writes the whole path rather than special paths like all previous versions of SF used to do correctly. Now this is what the path writes for example: ` "mainmenu", "24-7", "translatedPath", "ActivateWindow(Videos,\"plugin://plugin.program.super.favourites/?label=24-7&mode=400&path=C%3A%5CUsers%5Cxxx%5CAppData%5CRoaming%5CKodi%5Cuserdata%5Caddon_data%5Cplugin.program.super.favourites%5CSuper+Favourites%5C24-7&image=special%3A%2F%2Fhome%2Faddons%2Fresource.images.skinicons.wide%2Fresources%2Ficons%2F247.png&fanart=special%3A%2F%2Fhome%2Faddons%5Cplugin.video.fidoK19%5Cfanart.jpg&content_type=\",return)"`
> 
> I suspected that would be the case. My plan is to make the cache system ignore special paths which should resolve the issue you are reporting.

Awesome appreciate it. I rolled back SF to test this. I made the same main menu shortcut with the older version and it wrote the path correctly..
`         "mainmenu",
        "24-7",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.program.super.favourites/?label=24-7&mode=400&path=special%3A%2F%2Fprofile%2Faddon_data%2Fplugin.program.super.favourites%2FSuper+Favourites%5C24-7&image=special%3A%2F%2Fhome%2Faddons%2Fresource.images.skinicons.wide%2Fresources%2Ficons%2F247.png&fanart=special%3A%2F%2Fhome%2Faddons%5Cslyguy.plex.live%5Cfanart.jpg&content_type=\",return)",`

**Comment by jmooremcc** [comment]
Just released SF 2.3.4 which should resolve the issue with special paths.

**Comment by nebulous42069** [comment]
> Just released SF 2.3.4 which should resolve the issue with special paths.

Thank you for the partial fix!. I am now able to navigate and choose a thumbnail using special paths, however the issue still remains when you point to a Superfavorite using skin settings to make a shorcut, it still writes the full path rather than using special path.

**Comment by jmooremcc** [comment]
Could you make a video showing the steps you followed using skin settings so that I can replicate the issue. Thanks.

**Comment by nebulous42069** [comment]
> > > While your on the subject, another big flaw introduced with this new update. Every skin shortcut path or widget now uses the full OS file path. I was wondering why all my widgets and shortcuts that point to SF shortcuts no longer work on other devices. I create my setup on Windows 11 and then transfer the setup to other devices, and now none of those shortcuts will work because of this. Now when I create a shortcut to a SF folder using skin settings it writes the whole path rather than special paths like all previous versions of SF used to do correctly. Now this is what the path writes for example: ` "mainmenu", "24-7", "translatedPath", "ActivateWindow(Videos,\"plugin://plugin.program.super.favourites/?label=24-7&mode=400&path=C%3A%5CUsers%5Cxxx%5CAppData%5CRoaming%5CKodi%5Cuserdata%5Caddon_data%5Cplugin.program.super.favourites%5CSuper+Favourites%5C24-7&image=special%3A%2F%2Fhome%2Faddons%2Fresource.images.skinicons.wide%2Fresources%2Ficons%2F247.png&fanart=special%3A%2F%2Fhome%2Faddons%5Cplugin.video.fidoK19%5Cfanart.jpg&content_type=\",return)"`
> > 
> > 
> > I suspected that would be the case. My plan is to make the cache system ignore special paths which should resolve the issue you are reporting.
> 
> Awesome appreciate it. I rolled back SF to test this. I made the same main menu shortcut with the older version and it wrote the path correctly.. ` "mainmenu", "24-7", "translatedPath", "ActivateWindow(Videos,\"plugin://plugin.program.super.favourites/?label=24-7&mode=400&path=special%3A%2F%2Fprofile%2Faddon_data%2Fplugin.program.super.favourites%2FSuper+Favourites%5C24-7&image=special%3A%2F%2Fhome%2Faddons%2Fresource.images.skinicons.wide%2Fresources%2Ficons%2F247.png&fanart=special%3A%2F%2Fhome%2Faddons%5Cslyguy.plex.live%5Cfanart.jpg&content_type=\",return)",`

Sure, but im referring to the same issue as above, but I can make a video.

**Comment by nebulous42069** [comment]
Heres a video, just making any shortcut to a SF. First shortcut made with 2.3.4, second made after rolling back to 2.2.6.. https://video.hardlimit.com/w/5yAiiUEbqMH2p6Kix597ej

**Comment by jmooremcc** [comment]
I've released SF 2.3.5 which should resolve the issue you reported.

**Comment by nebulous42069** [comment]
> I've released SF 2.3.5 which should resolve the issue you reported.

Unfortunately, it seems 2.3.5 throws an error as soon as you open it. Tried a fresh install of Kodi, fresh install of your repo, SF throws an error. The only way to get it to open is by adding the full SF path in SF settings "Location of SF folder". 
`2023-10-01 14:18:46.290 T:2156    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'OSError'>
                                                   Error Contents: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'special://profile/addon_data/plugin.program.super.favourites/ImageCache'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\xxx\AppData\Roaming\Kodi\addons\plugin.program.super.favourites\default.py", line 199, in <module>
                                                       checkImageCacheStatus()
                                                     File "C:\Users\xxx\AppData\Roaming\Kodi\addons\plugin.program.super.favourites\imagecache.py", line 127, in checkImageCacheStatus
                                                       os.mkdir(IMAGECACHE)
                                                   OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'special://profile/addon_data/plugin.program.super.favourites/ImageCache'
                                                   -->End of Python script error report<--
                                                   
2023-10-01 14:18:46.308 T:2796     info <general>: CActiveAESink::OpenSink - initialize sink
2023-10-01 14:18:46.310 T:18884   error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.program.super.favourites/
2023-10-01 14:18:46.321 T:5836    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.program.super.favourites/) failed`

**Comment by nebulous42069** [comment]
Reports of the same issue are being made in the Kodi forum. Wish that user never suggested this image cache option, lol.

**Comment by nebulous42069** [comment]
Thank-you. It seems 2.3.6 fixed my issue. I will do more testing. Thanks again!!

**Comment by jmooremcc** [comment]
Issue resolved
